name: Test

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"

jobs:
  build:
    runs-on: ${{ matrix.os }} / ${{ matrix.python-version }}
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        os: [Ubuntu, MacOS, Windows]
        python-version: [3.7, 3.8, 3.9]
        poetry-version: [1.1.7]
        allow-failure: [false]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry config experimental.new-installer false
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run tests
        run: |
          poetry run pytest tests/ -p no:cov -o addopts=""
